### ISSUE TITLE
I'd like to open all issues that are in "cart" 

### ISSUE THREAD

**Issue by jama22** [vito/cadet#50]
<img width="463" alt="screen shot 2018-06-11 at 10 49 56 am" src="https://user-images.githubusercontent.com/19274230/41238941-341ad06a-6d65-11e8-85cc-06434b1956ce.png">

# Proposal
I tend to do a bit of triaging in Cadet and my workflow looks a bit like this:
1. Click on a bunch of issues that are untriaged so they show up in Cart
2. Click on issues individually in new tabs
3. Go through new tabs to triage issue
4. Rinse and repeat

It would be nice if i could add a bunch of issues to cart and then using a single button open all links in a new tab, without having to go through them individually

**Comment by vito** [comment]
no
